# Geary Email Client
#
# Purpose: Lightweight email client designed for GNOME desktop
# Platform: Linux (GNOME)
#
# Geary is the modern, lightweight email client for GNOME 3+
# - Simple, focused email experience
# - Perfect GNOME desktop integration
# - Modern design following GNOME HIG
#
# Configuration:
# - Pre-configures Proton Bridge account (IMAP/SMTP server settings)
# - Email resolved from user.email (supports secrets)
# - Bridge password optionally stored in GNOME Keyring via protonPassword secret
#   (password is unique per machine, generated by protonmail-bridge)
#
# Dependencies:
# - user.email: Email address to configure
# - user.security.protonPassword (optional): bridge password for auto-keyring setup
#
# Constitutional: <200 lines, uses lib.mkDefault
#
# Usage:
# Add "geary" to user.workspace.applications array
# For Proton Bridge: complete bridge setup first, then launch Geary
# and enter the bridge password from: protonmail-bridge --cli → info
{
  config,
  pkgs,
  lib,
  ...
}: let
  secrets = import ../../../../../../user/lib/secrets.nix {inherit lib pkgs;};
  emailLib = import ../../../../lib/email.nix {inherit lib;};

  email = config.user.email or null;
  hasEmail = email != null;
  isProtonBridge = emailLib.isProtonEmail email;
in {
  # Install Geary email client
  home.packages = [pkgs.geary];

  # Configure Geary dconf settings
  dconf.settings = lib.mkIf hasEmail {
    "org/gnome/Geary" = {
      run-in-background = lib.mkDefault true;
      startup-notifications = lib.mkDefault true;
    };
  };

  # Pre-configure Geary account for Proton Bridge (server settings only)
  # Password must be entered manually on first launch (unique per machine)
  home.activation.configureGearyAccount = lib.mkIf isProtonBridge (
    secrets.mkActivationScript {
      inherit config pkgs lib;
      name = "geary-proton";
      fields = {
        email = ''
          ACCOUNT_DIR="$HOME/.config/geary/account_01"
          mkdir -p "$ACCOUNT_DIR"

          cat > "$ACCOUNT_DIR/geary.ini" << GEARYEOF
          [AccountInformation]
          real_name=${config.user.fullName or config.user.name or ""}
          nickname=Proton Mail
          service_provider=OTHER
          ordinal=0
          prefetch_period_days=14
          save_drafts=true
          imap_host=127.0.0.1
          imap_port=1143
          imap_ssl=false
          imap_starttls=false
          imap_username=$EMAIL
          imap_remember_password=true
          smtp_host=127.0.0.1
          smtp_port=1025
          smtp_ssl=false
          smtp_starttls=false
          smtp_username=$EMAIL
          smtp_noauth=false
          smtp_remember_password=true
          GEARYEOF
        '';
        "security.protonPassword" = ''
          # Store bridge password in GNOME Keyring for Geary
          if command -v secret-tool >/dev/null 2>&1; then
            echo -n "$SECURITY_PROTONPASSWORD" | secret-tool store --label="Geary account_01 imap-password" geary-imap-password account_01
            echo -n "$SECURITY_PROTONPASSWORD" | secret-tool store --label="Geary account_01 smtp-password" geary-smtp-password account_01
          fi
        '';
      };
    }
  );

  # Set as default email client
  xdg.mimeApps.defaultApplications = {
    "x-scheme-handler/mailto" = "org.gnome.Geary.desktop";
    "message/rfc822" = "org.gnome.Geary.desktop";
  };

  # Shell aliases for convenience
  home.shellAliases = {
    mail = "geary";
    email = "geary";
  };

  # Warnings
  warnings =
    lib.optional (!hasEmail) ''
      Geary: user.email not configured.
    ''
    ++ lib.optional (isProtonBridge && ((config.user.security or {}).protonPassword or null) == null) ''
      Geary: Proton Bridge account pre-configured (127.0.0.1:1143/1025).
      To auto-configure password: just secrets-set <user> security.protonPassword "<password>"
      Or enter manually on first launch. Get password from: protonmail-bridge --cli → info
    '';
}
