# Systemd Service Contract: nix-config-first-boot.service
#
# Purpose: Define the systemd service configuration that blocks graphical.target
#          until home-manager activation completes on first boot
#
# Location: system/nixos/settings/system/first-boot.nix
# Context: System-level (NixOS configuration)

{
  config,
  lib,
  pkgs,
  ...
}: {
  systemd.services.nix-config-first-boot = {
    # Human-readable description
    description = "First boot home-manager setup";

    # Dependency: Service is enabled and starts during multi-user.target
    wantedBy = ["multi-user.target"];

    # Ordering: Start after network is available
    after = ["network-online.target"];
    wants = ["network-online.target"];

    # CRITICAL: Block graphical.target until this service completes
    # This prevents GDM from starting until home-manager activation finishes
    before = ["graphical.target"];  # ← NEW LINE (core fix)

    # Conditional execution: Only run if marker file exists
    # Marker file created during nixos-install, removed after first run
    unitConfig = {
      ConditionPathExists = "/home/${config.user.name}/.nix-config-first-boot";
    };

    # Service behavior
    serviceConfig = {
      # Type: oneshot - Service must complete before dependent units start
      # This makes graphical.target WAIT for completion (blocking behavior)
      Type = "oneshot";

      # Execute as target user (not root) to access agenix key
      User = config.user.name;
      Group = "users";

      # Activation script location (generated by NixOS module)
      ExecStart = "/etc/nix-config-first-boot.sh";

      # RemainAfterExit: Keep service "active" after script exits
      # This satisfies graphical.target dependency even after completion
      RemainAfterExit = true;

      # Logging: Send stdout/stderr to systemd journal
      StandardOutput = "journal";
      StandardError = "journal";

      # Environment: Provide PATH and HOME for script execution
      Environment = [
        "PATH=/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/run/wrappers/bin:${pkgs.git}/bin:${pkgs.nix}/bin:${pkgs.coreutils}/bin"
        "HOME=/home/${config.user.name}"
      ];
    };
  };
}

# Contract Properties:
#
# GUARANTEES:
# - Service runs BEFORE graphical.target (GDM blocked until completion)
# - Service runs AFTER network is available (can clone repository)
# - Service runs ONCE per installation (condition prevents re-runs)
# - Service execution is BLOCKING (Type=oneshot + before directive)
# - Service remains "active" after completion (RemainAfterExit=true)
#
# DEPENDENCIES:
# - Requires: network-online.target (soft dependency via wants)
# - Requires: /home/{user}/.nix-config-first-boot marker file
# - Requires: /etc/nix-config-first-boot.sh activation script
# - Requires: ~/.config/agenix/key.txt for secret decryption
#
# FAILURE MODES:
# - Network unavailable: Service skips gracefully (wants, not requires)
# - Build failure: Service exits non-zero, graphical.target starts anyway
# - Timeout: No timeout defined (service can run indefinitely)
#
# VERIFICATION:
# - Check ordering: systemctl show -p Before nix-config-first-boot.service
# - Check execution: journalctl -u nix-config-first-boot.service
# - Check completion: systemctl status nix-config-first-boot.service
# - Check won't re-run: test ! -f ~/.nix-config-first-boot
